<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True" SettingsObjectName="受付入力システム.Properties.Settings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.School" Member="School">
    <Type Name="School">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="School_Student" Member="Student" ThisKey="Id" OtherKey="SchoolId" Type="Student" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Student">
    <Type Name="Student">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SchoolId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Column Name="Grade" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KanaName" Type="System.String" DbType="NVarChar(63)" CanBeNull="true" />
      <Column Name="Sei" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="School_Student" Member="School" ThisKey="SchoolId" OtherKey="Id" Type="School" IsForeignKey="true" />
    </Type>
  </Table>
</Database>